### ISSUE TITLE
Create minimal click command

### ISSUE THREAD

**Issue by gravesm** [ehanson8/archivesspace-api#23]
The main reason to go ahead and start working on the click command is so we can make the client configuration more flexible. We want to move away from requiring a configuration file to pulling configuration from command line options and/or environment variables. This will make configuring the test suite and containerizing the app much easier. You'll still be able to use a local file for configuration because you can set any environment variables in a `.env` file in your project root and pipenv will load those by default.

The easiest way to do this will be to use the `envvar` option is click options: https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables. An example of what this will look like with click:

```python
@click.command()
@click.option('--url', envvar='ARCHIVESSPACE_URL')
def main(url):
    client = ASnakeClient(baseurl=url)
```

I usually put the click command in a file called `cli.py`. That's relatively common. I've also seen people use `main.py` and `command.py`.

**Comment by ehanson8** [comment]
I will want to discuss the most efficient way to switch between dev and prod through the environmental variables

**Comment by ehanson8** [comment]
Closing after PR #27
