### ISSUE TITLE
Refactor client

### ISSUE THREAD

**Issue by gravesm** [ehanson8/archivesspace-api#24]
Having spent some time looking at the `ASnakeClient` I think we should make a few changes to our `Client` class. Rather than making this a client, we'll make it a thing that uses a client. I'd probably change the name to something like `ASRepo` but you can leave it as `Client` if you want. A rough idea of functionality it should provide:

```python
class ASRepo:
    def __init__(self, client):
        self.client = client
    def get_record(self, uri):
        ...
    def search(self, **kwargs):
        ...
    def save(self, record):
        ...
```

The biggest difference here is that instead of creating the client it will take an already configured client. We'll configure the client elsewhere in the application. The fancy term for this pattern is dependency injection. It's one of the main tools we have for keeping applications loosely coupled.

**Comment by ehanson8** [comment]
Closing after PR #27
