### ISSUE TITLE
Add test for get_record

### ISSUE THREAD

**Issue by gravesm** [ehanson8/archivesspace-api#25]
Getting the test suite working for the `get_record` method will be a good place to start since this will require us to get our client configured and our HTTP mocking set up. We'll be able to use the same approach elsewhere in our test suite. For HTTP mocking I'd suggest either VCR or requests-mock. I don't have much experience with VCR, but that shouldn't stop you from using it.

**Comment by ehanson8** [comment]
Closing after PR #27
