### ISSUE TITLE
Remove json_string property

### ISSUE THREAD

**Issue by gravesm** [ehanson8/archivesspace-api#34]
We should start moving away from editing the json_string property in the BaseRecord. The JSON we get back from a request will be used to populate a model, but then we want to discard it. Once it's been turned into our model, we don't need it anymore. When we're ready to save our changes, we'll serialize the model to JSON. We may need to do some work to ensure the serialized JSON looks like what we want, but we want to be working with our model as a real model.

**Comment by ehanson8** [comment]
This was reconsidered after a discussion about the complexity of the AS data model and the lack of a PATCH operation for the AS API
