### ISSUE TITLE
What is the license for these scripts?

### ISSUE THREAD

**Issue by jeremyf** [ehanson8/archivesspace-api#66]
Is there any associated license with this repository? My team is working on interacting with the ArchivesSpace API and may be interested in using/referencing these scripts.

**Comment by ehanson8** [comment]
I'm currently refactoring these scripts in this [branch](https://github.com/MITLibraries/archivesspace-api-python-scripts/tree/app-refactor) which has the Apache 2.0 License and I encourage any and all reuse! The code is much cleaner on this branch but it's set up more as a command line application which may or may not be appropriate for your needs. Let me know if you have any other questions!

**Comment by jeremyf** [comment]
Can the license be added to the master branch? This would help provide clarity for those coming to the project.

**Comment by ehanson8** [comment]
Yes, I'll do that

**Comment by ehanson8** [comment]
Added the license, let me know if other questions come up!
